databases:
  - name: JokerData
    ipAllowList: []
    region: frankfurt
    plan: free
services:
  - type: web
    plan: free
    name: Joker
    env: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: python3 ser.py & python3 -m JoKeRUB
    region: frankfurt
    envVars:
      - key: APP_ID 
        value: 9514755
      - key: API_HASH 
        value: 40e7041d06ea7b6ee1cf39b3188b3452
      - key: ENV 
        value: ANYTHING
      - key: STRING_SESSION
        sync: false
      - key: TG_BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: TZ
        value: Asia/Baghdad 
      - key: DATABASE_URL
        fromDatabase:
          name: JokerData
          property: connectionString   
    autoDeploy: false
